apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
      - name: test-volume
        configMap:
            name: test-config
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: test-volume
      

